### ISSUE TITLE
Merge BlockPlacer branch.

### ISSUE THREAD

**Issue by xbony2** [Esteemed-Innovation/Esteemed-Innovation#212]
It would be good to see if we can merge the block placer branch with master. The block placer was created for a need to automate the rock smasher without another mod, according to @Zenith-One.

Also we should delete some branches that don't have any changes.

**Comment by satanicsanta** [comment]
1. I don't think it actually works. Could be wrong though, you should test it.
2. Yes.

**Comment by Zenith-One** [comment]
It's not entirely done for sure. It's somewhat close, but it doesn't have any rendering code attached.

**Comment by xbony2** [comment]
I'll see if I can finish it and merge it manually.

**Comment by Gholuk** [comment]
I am running the block placer for several weeks already. It's working good and I think I only copy&pasted the code without doing any changes.

But some recommendations:
First: Redstone Support to stop the block placer
Second: It may be a good idea to place blocks without TileEntity only. Auto-Placing blocks with TE could cause strange results and unwanted side-effects.
For example: It may enable you to place saplings/plants on or under water or other weird underground, because all validation checks for placement are skipped. People could build a complete forest in the ocean.
Other example: If you place a gauge with the placer, it will face the default direction and accordingly try to get a pressure value from the block next to it. If this block does not support a gauge, you cause a server crash due to NullPointer Exception.
So you should only allow blocks without TileEnity or do a whitelist for TEs that will not cause trouble.

**Comment by xbony2** [comment]
Got the tile-entity issue fixed.

**Comment by xbony2** [comment]
I made a pretty simple texture. If anyone wants to improve it, go ahead.

**Comment by elifoster** [comment]
Okay so it was actually added into the base branch at some point. I have absolutely no idea when this was, but I know I've worked on it (and I'm working on it now). Since it is basically functioning and has been in base for a while, closing this and deleting the branch.
